version: '3.9'

services:
  db:
    image: 'postgres'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: '12345678'
      POSTGRES_USER: 'admin'
      POSTGRES_DB: 'monke'
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: